[[constraint]]
  name = "istio.io/api"
  branch = "master"

[[constraint]]
  name = "istio.io/istio"
  branch = "release-1.1"

# [[constraint]]
#   name = "k8s.io/api"
#   version = "kubernetes-1.10.4"

# [[constraint]]
#   name = "k8s.io/apimachinery"
#   version = "kubernetes-1.10.4"

# [[constraint]]
#   name = "k8s.io/apiextensions-apiserver"
#   version = "kubernetes-1.10.4"

# [[constraint]]
#   name = "k8s.io/cluster-registry"
#   version = "0.0.3"

# [[constraint]]
#   name = "k8s.io/helm"
#   version = "2.9.1"

# [[constraint]]
#   name = "k8s.io/ingress"
#   version = "0.9.6"

# [[constraint]]
#   name = "k8s.io/kubernetes"
#   version = "v1.10.4"

# https://github.com/kubernetes/client-go#compatibility-matrix
# for details.
[[override]]
  name = "k8s.io/client-go"
  branch = "release-8.0"        # For K8s 1.10.x

# matching client-go kubernetes-1.11.3's
[[override]]
  name = "github.com/Azure/go-autorest"
  revision = "bca49d5b51a50dc5bb17bbf6204c711c6dbded06"

